In [1]:
import numpy as np

In [13]:
# Deep copy vs shallow copy

'''
shallow copy - reshape, a.view()
deep copy - operators, a.copy()
'''

a=np.arange(12)
b=a.reshape(3,4)
c=a+2
d=a[a>4]

print(a)
print(b)
print(c)
print(d)


print(np.shares_memory(a,b))
print(np.shares_memory(a,c))
print(np.shares_memory(a,d))

b[0][1]=111

print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  3  4  5  6  7  8  9 10 11 12 13]
[ 5  6  7  8  9 10 11]
True
False
False
[  0 111   2   3   4   5   6   7   8   9  10  11]
[[  0 111   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [17]:
# Make seperate arrays for seperate columns

raw=np.loadtxt(r'C:\Users\28962\Documents\GitHub\DSML\7_data_analytics_and_visualisation\7.7_numpy_remedial_and_refresher\fit.txt','str')

date,step_count,mood,calories_burnt,hours_sleep,active = raw.T

C:\Users\28962\AppData\Local\Temp\ipykernel_1116\1339526139.py:3: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  raw=np.loadtxt(r'C:\Users\28962\Documents\GitHub\DSML\7_data_analytics_and_visualisation\7.7_numpy_remedial_and_refresher\fit.txt','str')


In [22]:
# argmax and argmin: provide index of max and min values

print(calories_burnt[np.argmax(calories_burnt)])
print(date[np.argmax(calories_burnt)])
print(calories_burnt[np.argmin(calories_burnt)])
print(date[np.argmin(calories_burnt)])


99
23-10-2017


# Multiplication

## Rule: (a,b).(c,d): b should always be equal to c

In [26]:
# 1d vs 1d

a=np.arange(12)
b=np.arange(1,13)

print(np.matmul(a,b) )
print(np.dot(a,b))

572
572


In [41]:
# 1d vs 2d
c=np.arange(3)
d=np.arange(1,13).reshape(3,4)

print(c,c.shape)
print(d,d.shape)

print(np.dot(c,d)) 
# print(np.dot(d,c)) # This isnt following the rule

[0 1 2] (3,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[23 26 29 32]


# NP vectorization


In [51]:
# Vectorization helps us to use array element wise for a function

def test(k):
    if k%2==0:
        k+=2
    else:
        k+=3
    return(k)

e=np.arange(3)

# test(e) # this  will give error because no vectorization

func=np.vectorize(test)
func(e)


array([2, 4, 4])

## Questions

In [ ]:
'''
Q -8

Given an MxN 2D array (M >= 4),

Split the array column wise such that,

1st sub array contains the first 2 columns
2nd sub array contains the 3rd column
3rd sub array contains the rest of the columns
'''