In [6]:
# Extract multiple elements from an array using index

import numpy as np
a=np.array([1,2,3,4,5,6])
print(a[[2,-1,-2]])

[3 6 5]


In [9]:
# np array slicing 
b=np.array([1,2,3,4,5])
print(b[3:-5:-1])

print (b[1:3:-1]) # Note this emty array because there is no direction to move towards. In case of list, this would have given error

[4 3 2]
[]


In [14]:
# Assignment/broadcasting - from array and from single element

c=np.array([1,2,3,4,5,6,7,8,9])
c[0:3]=[100,111,222]
print(c)

d=np.array([1,2,3,4,5,6,7])
d[0:3]=1000
print(d)

[100 111 222   4   5   6   7   8   9]
[1000 1000 1000    4    5    6    7]


In [15]:
# Masking/fancy slicing
e=np.array([1,2,3,4,5,6])
print(e[e>3])

[4 5 6]


In [16]:
# Assignment along with masking

f=np.array([1,2,3,4,5,6])
f[f>2]=100
print(f)

[  1   2 100 100 100 100]


In [18]:
# Negative masking with tilda
g=np.array([1,2,3,4,5,6,7])
print(g[~g%2==0])

[1 3 5 7]


In [20]:
# Multiple masking - dont use 'and' but instead &. That's because 'and' performs operation between objects whereas '&' performs element wise operation bw 2 arrays

h=np.array([1,2,3,4,5,6])
print(h[(h>2)&(h<5)])

[3 4]


In [32]:
# Mathematical functions like mean, sum , sort

i=np.array([2,1,5,4,3,6,7])
print(np.mean(i))
print(np.sum(i))
j=np.sort(i)
print(i)
print(j)

4.0
28
[2 1 5 4 3 6 7]
[1 2 3 4 5 6 7]


In [39]:
# to get number of elements always use shape instead of length. Because shape is meta data of an array where a count is an aggregate method

k=np.array([1,2,3,4,5,6,7])
print(k.shape[0])
print(len(k))

7
7


In [ ]:
# Gdown: to download data from google drive 

!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: c:\Users\28962\Documents\GitHub\DSML\7_data_analytics_and_visualisation\7.2_numpy_2_fitbit_analysis\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|██████████| 2.55k/2.55k [00:00<?, ?B/s]


In [43]:
l=np.loadtxt(r'c:\Users\28962\Documents\GitHub\DSML\7_data_analytics_and_visualisation\7.2_numpy_2_fitbit_analysis\survey.txt')

array([ 7., 10.,  5., ...,  5.,  9., 10.])