In [42]:
# Empty array: Important to mention dtype and shape

import numpy as np
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
a=np.loadtxt(r'c:\Users\28962\Documents\GitHub\DSML\7_data_analytics_and_visualisation\7.3_numpy_2_fitbit_analysis_comt\survey.txt')
b=np.empty(shape=[a.shape[0],],dtype='U25')
b[a>7]='Promoters'
b[a<5]='Detractors'
b[(a>=5)&(a<=7)]='mid'
print(a,b)

[ 7. 10.  5. ...  5.  9. 10.] ['mid' 'Promoters' 'mid' ... 'mid' 'Promoters' 'Promoters']


Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: c:\Users\28962\Documents\GitHub\DSML\7_data_analytics_and_visualisation\7.3_numpy_2_fitbit_analysis_comt\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|██████████| 2.55k/2.55k [00:00<?, ?B/s]


In [40]:
# Unique values with return counts and make a dictionary for these

c=np.array([1,1,2,2,2,2,3,4,5,6,6,6])
d=np.unique(c,return_counts=True)
dict={}
dict[d[0][0]]=d[1][0]
dict[d[0][1]]=d[1][1]
dict[d[0][2]]=d[1][2]

In [52]:
# slice, reshape of 2-d array and len of 2d arry will give number of 1st dimension elements

e=np.arange(12).reshape(3,4)
print(e)
print(e[1:,:2])
print(len(e))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[4 5]
 [8 9]]
3


In [54]:
# Flatten
f=np.arange(12).reshape(3,-1)
print(f)
print(f.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [59]:
# Transpose. No transpose for 1d array, why?

g=np.arange(12).reshape(4,-1) # Reshape with unknown column or rows 
print(g)
print(g.T)
print(g.flatten())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [60]:
# Masking of 2d array: always returns 1d array

h = np.arange(12).reshape(4,-1)
print(h[h>5])

[ 6  7  8  9 10 11]


In [62]:
# Axis parameter - needed for operations like sum, min, sort

i = np.arange(12).reshape(3,-1)
print(i)
print(np.sum(i))
print(np.sum(i,axis=0))
print(np.sum(i,axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [64]:
# Indexing for single and multiple elements

j= np.arange(12).reshape(3,-1)
print(j)
print(j[1,2])
print(j[(1,2),(1,2)])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[ 5 10]


# Problems

In [65]:
'''

1 - Given an array in form of a matrix of size (n, n), rotate the matrix clockwise by 90º

Sample Input:

[[1 2 3] 
 [4 5 6]
 [7 8 9]]

 Sample Output:

[[7 4 1]
 [8 5 2]
 [9 6 3]]

'''
import numpy as np
def rotate_img(mat):
   a=mat
   return(np.transpose(mat[::-1]))


In [83]:
'''
    
2 - Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)

birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
    
    
'''

import numpy  as np

def sort_birds(birds, age):
    result=birds[np.argsort(age)]
    return result



birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

sort_birds(birds, age)


array(['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
       'spoonbills', 'Cranes', 'plovers', 'spoonbills'], dtype='<U10')

In [92]:
'''
3 - Given a M x N array, Perform the following operations:
1. Get the odd rows from the array i.e. 1st, 3rd, 5th etc..
2. Convert the above result into 1D array and return it.
'''
import numpy as np 
def test(arr):
    result=arr[::2].flatten()
    return(result)
a=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

test(a)


array([1, 2, 3, 7, 8, 9])