In [ ]:
'''
1d array - vector
2d array - matrixS
3d array - tensor

'''

In [3]:
# interesting problem 1

import numpy as np
a=np.arange(12).reshape(3,4)

print(a)
print(np.sum(a[:2],axis=1))
print(np.sum(a[:2],axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22]
[ 4  6  8 10]


In [7]:
# interesting problem 2

# diognal elements 

b=np.arange(16).reshape(4,4)
b_up= [b[i,i] for i in range(b.shape[0])]

In [19]:
# interesting problem 3

# swap 1st and 2nd row

c=np.arange(12).reshape(3,4)
print(c)
c[[0, 1]] = c[[1, 0]]

print(c)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


In [22]:
'''

1 - output of the below code

import numpy as np
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis], mask])

'''

# 0,2
# 4,6
# 8,10