In [ ]:
'''
by default every class passes an argument that points to itself

'''

In [2]:
import numpy as n

In [4]:
# class and object variables
class student:
    school = 'dps'

    def __init__(self,name,age):
        self.name=name
        self.age=age

a=student('mayank',25)
b=student('pankaj',35)

print(student.school)
print(a.school)
print(b.school)

b.school='Christ king'

print(student.school)
print(a.school)
print(b.school)

# NOTICE HOW ONLY B OBJECT'S SCHOOL IS GETTING CHANGED AND NOT OBJECT VARIABLE. THIS IS BECAUSE OBJECT VARIABLE IS UNMUTABLE

dps
dps
dps
dps
dps
Christ king


In [8]:
class dogs:
    tricks=[]

    def __init__(self,name):
        self.type=type
        self.name=name
    
    def trick(self,trick):
        self.tricks.append(trick)

c=dogs("tommy")
d=dogs("Jayanti")

print(dogs.tricks)
print(c.tricks)
print(d.tricks)

c.trick('flip')

print(dogs.tricks)
print(c.tricks)
print(d.tricks)


# NOTICE HERE ALL VARIABLES (C,D AND CLASS) ARE GETTING UPDATED. tHIS IS BECAUSE LISTS ARE MUTABLE



[]
[]
[]
['flip']
['flip']
['flip']


In [8]:
'''
Q4 
'''

arr = np.array([1,2,3,0,-2,4])
arr2 = arr*1
arr3 = arr[:]
arr4 = arr[arr > 0]
arr5 = arr.reshape(2,3)

np.shares_memory(arr,arr5)

True

In [2]:
import numpy as np
arr = np.arange(16).reshape(4,4)  
print(np.split(arr,4))
a,b,c,d=np.split(arr,4)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [10]:
np.split(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]