In [2]:
import numpy as np

In [8]:
'''
Q4 
'''

arr = np.array([1,2,3,0,-2,4])
arr2 = arr*1
arr3 = arr[:]
arr4 = arr[arr > 0]
arr5 = arr.reshape(2,3)

np.shares_memory(arr,arr5)

True

In [9]:
import numpy as np
arr = np.arange(16).reshape(4,4)  
print(np.split(arr,4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [10]:
np.split(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]