# Numpy

In [ ]:
# tutor's colab - https://colab.research.google.com/drive/1YQ1I-76tK6saBU6BgcWJ3FGKkr9I2CZy?usp=sharing

import pandas as pd
import numpy as np

In [10]:
# Q1 - Create a mask to select elements greater than 3 and less than 8, and then replace those elements with their square roots

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[(arr>3)& (arr < 8)]=np.sqrt(arr[(arr>3)& (arr < 8)])
arr

array([[1, 2, 3],
       [2, 2, 2],
       [2, 8, 9]])

In [ ]:
# Q2 - Consider a 1D NumPy array arr = np.array([1, 2, 3, 4, 5]). Rotate the elements of the array one position to the left.

import numpy as np 
arr = np.array([1, 2, 3, 4, 5])

a = arr[:1]
b = arr[1:]


np.concatenate((b,a))


array([2, 3, 4, 5, 1])

In [22]:
# Q3: Given a 1D NumPy array arr = np.array([10, 5, 8, 12, 3]), find the indices that would sort the array in

arr=np.array([10, 5, 8, 12, 3])

np.argsort(arr)

array([4, 1, 2, 0, 3])

In [23]:
# Q4: Given two 2D NumPy arrays a and b: compute dot product 

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [24]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [27]:
# Q5: Consider a 2D NumPy array arr as follows: Select the elements at indices (0, 2), (1, 1), (2, 0) in the array.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[[0,1,2],[2,1,0]]

array([3, 5, 7])

# Pandas

In [ ]:
# Q1: Using the Seaborn dataset "tips", find the average total bill amount ("total_bill") for each day ("day") of the week.

In [32]:
import seaborn as sns

tips = sns.load_dataset("tips")
tips

tips.groupby('day')['total_bill'].mean()

C:\Users\28962\AppData\Local\Temp\ipykernel_13692\1519569549.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('day')['total_bill'].mean()


day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [33]:
'''Q2: Using the Seaborn dataset "tips", find the average total bill amount ("total_bill") for each day ("day") of the week,
but only consider the data where the number of people ("size") is greater than 2.'
'''
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
(tips[tips['size']>2]).groupby('day')['total_bill'].mean()

C:\Users\28962\AppData\Local\Temp\ipykernel_13692\3716945383.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  (tips[tips['size']>2]).groupby('day')['total_bill'].mean()


day
Thur    27.594615
Fri     28.075000
Sat     27.365938
Sun     25.468108
Name: total_bill, dtype: float64

In [35]:
'''
Q3: Using the Seaborn dataset "diamonds",
filter the data to only include diamonds with a carat weight ("carat") between 0.8 and 1.2 (inclusive) and a clarity ("clarity") of "IF" (Internally Flawless).
'''
dm = sns.load_dataset("diamonds")
dm

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [36]:
dm[(dm['carat']>=0.8)&(dm['carat']<=1.2)&(dm['clarity']=='IF')]

carat        cut color clarity  depth  table  price     x     y     z
2615    0.82    Premium     I      IF   61.2   60.0   3224  6.03  5.99  3.68
3252    0.80      Ideal     I      IF   62.4   58.0   3357  5.90  5.96  3.70
4647    0.90       Good     I      IF   63.7   64.0   3669  6.07  6.02  3.85
4699    0.90      Ideal     J      IF   62.2   57.0   3677  6.17  6.14  3.83
4960    0.90       Good     I      IF   63.7   64.0   3734  6.02  6.07  3.85
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
27455   1.14  Very Good     D      IF   59.1   58.0  18112  6.83  6.90  4.06
27457   1.07  Very Good     D      IF   60.9   58.0  18114  6.57  6.67  4.03
27507   1.09  Very Good     D      IF   61.7   58.0  18231  6.55  6.65  4.07
27530   1.07    Premium     D      IF   60.9   58.0  18279  6.67  6.57  4.03
27635   1.04  Very Good     D      IF   61.3   56.0  18542  6.53  6.55  4.01

[198 rows x 10 columns]

In [ ]:
'''
Q5: Using the Seaborn dataset "iris",
find the median petal width ("petal_width") for each species ("species") and each petal length ("petal_length") category.
'''


iris = sns.load_dataset("iris")

iris.groupby(['species',pd.cut(iris['petal_length'],2)])['petal_width'].median()

C:\Users\28962\AppData\Local\Temp\ipykernel_6628\115326167.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  iris.groupby(['species',pd.cut(iris['petal_length'],2)])['petal_width'].median()


species     petal_length 
setosa      (0.994, 3.95]    0.2
            (3.95, 6.9]      NaN
versicolor  (0.994, 3.95]    1.1
            (3.95, 6.9]      1.4
virginica   (0.994, 3.95]    NaN
            (3.95, 6.9]      2.0
Name: petal_width, dtype: float64