In [ ]:
# np.new_axis
# splitting of an array
# np.new_axis

# np.vectorization

# none as attribute
# randint
# np.concatenate

# hstack, vstack, hsplit, vsplit

# a.squeeze
# np.expand_dims


In [2]:
import numpy as np

In [12]:
# 1d vs 1d
# normal sum product 

a=np.arange(3)
b=np.arange(3)
print(a.shape,b.shape)

print(a,b,np.dot(a,b))

(3,) (3,)
[0 1 2] [0 1 2] 5


In [31]:
# 1d vs 2d
# for shapes (3,) and (3,3), final product would be (3,). i.e row vector

c=np.random.randint(0,10,[3])
d=np.random.randint(0,10,[3,3])
d_err=np.random.randint(0,10,[4,3])

print(c,d,c.shape,d.shape,np.dot(c,d),np.dot(c,d).shape)
# print(c,d,c.shape,d.shape,np.dot(c,d_err),np.dot(c,d_err).shape) 
    # this will give error  because shape mismatch

[3 0 1] [[4 8 6]
 [5 5 8]
 [8 2 7]] (3,) (3, 3) [20 26 25] (3,)


In [4]:
# 2d vs 1d
# for shapes (3,3) and (3,), final product would be (3,). i.e row vector
# BASICALLY, FOR ANY 1D VS 2D DOT PRODUCT, FUNAL PRODUCT WILL BE 1D ONLY AND THAT WILL BE ROW VECTOR

e=np.random.randint(0,10,[3])
f=np.random.randint(0,10,[4,3])

print(e,f,e.shape,f.shape,np.dot(f,e),np.dot(f,e).shape)

[2 3 0] [[2 3 5]
 [7 0 1]
 [1 4 1]
 [4 2 5]] (3,) (4, 3) [13 14 14 14] (4,)


In [32]:
# 2d vs 2d

# for shapes (2,3) and (3,4), final product would be (2,4).i.e another 2d vecotr

g=np.random.randint(0,10,[2,3])
h=np.random.randint(0,10,[3,4])

print(g,h,g.shape,h.shape,np.dot(g,h),np.dot(g,h).shape) # this will become 2d vector of 2,4 shape


[[9 7 6]
 [1 1 1]] [[2 8 6 6]
 [4 1 6 5]
 [3 9 8 3]] (2, 3) (3, 4) [[ 64 133 144 107]
 [  9  18  20  14]] (2, 4)
